FROM demo-docker:1

USER root
ENTRYPOINT ["sh", "-c", "xhost +local:user:docker:root"]
RUN mkdir -p home/face_recognition
# RUN mkdir -p home/face_recognition/data
WORKDIR /home/face_recognition
COPY datacreate.py /home/face_recognition

CMD [ "python", "/home/face_recognition/datacreate.py" ]
