apiVersion: apps/v1
kind: Deployment
metadata:
  name: recog-deployment
  labels:
    app: recognition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recognition
  template:
    metadata:
      labels:
        app: recognition
    spec:
      containers:
      - name: recognition
        image: localhost:5000/recog
        imagePullPolicy: IfNotPresent
        tty: true
        env:
        - name: DISPLAY
          value: unix:0
        volumeMounts:
        - mountPath: /dev/video0
          name: video
        - mountPath: /home/face_recognition/data
          name: data
        - mountPath: /tmp/.X11-unix
          name: screen
        securityContext:
          privileged: true
        ports:
        - containerPort: 8000
          hostPort: 8000
      volumes:
      - name: video
        hostPath:
          path: /dev/video0
      - name: data
        hostPath:
          path: /etc/kubeedge/data
      - name: screen
        hostPath:
          path: /tmp/.X11-unix
      hostNetwork: true
      nodeSelector:
        dedicated: edge

